app/Http/routes.php
<?php

use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');


Route::get('auth/logout', 'Auth\AuthController@getLogout');

Route::get('auth/register', array('as' => '/auth/register', 'uses' => 'Auth\AuthController@getRegister'));
Route::post('auth/register', 'Auth\AuthController@postRegister');

Route::filter('auth', function(){

    if (Auth::guest()) return Redirect::to('auth/login');

});

Route::controllers([
    'password' => 'Auth\PasswordController',
]);

Route::group(array('before' => 'auth'), function(){

    Route::get('/', array('as' => '/', 'uses' => 'HomeController@index'));

    Route::get('/studenti/lista/',array('as' => '/lista', 'uses' => 'StudentiController@showPredmeti'));



    Route::resource('/profesori', 'ProfesoriController');

    Route::resource('/predmeti', 'PredmetiController');

    Route::resource('/profil', 'ProfilController');

    Route::resource('/studenti', 'StudentiController');

    Route::get('/home', array('as' => '/home', 'uses' => 'HomeController@index'));


});




// varuiable via route get back

resources/views/root/home.blade.php
@extends('top')
@extends('navbar')


@section('content')


    @if (Session::has('loginMessage'))
        <div class="alert alert-success">{{ Session::get('loginMessage') }}</div>
    @endif

@stop

@extends('bottom')

resources/views/root/pred_studenti.blade.php
@extends('top')
@extends('navbar')
@section('content')


    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading" style="text-align: center;"><h1>Листа на студенти</h1></div>
                    <div class="panel-body">

                        @if(Session::has('message'))
                            <div class="alert alert-success">
                                {{ Session::get('message') }}
                            </div>
                        @endif

                            @foreach($predStudenti as $predStud)
                                <li class="list-group-item" id="">{!! $predStud['predmet'] !!}
                                @foreach($predStudenti as $predStud)
                                    <ul>
                                        <li class="list-group-item" id="">{!! $predStud['celoime'] !!}</li><br>
                                    </ul>
                                 @endforeach
                                </li><br>
                            @endforeach


                    </div></div></div></div></div>

@stop

@extends('bottom')

resources/views/root/predmeti.blade.php
@extends('top')
@extends('navbar')
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading" style="text-align: center"><h1>Листа на предмети</h1></div>
                    <div class="panel-body">

                        @if(Session::has('message'))
                            <div class="alert alert-success">
                                {{ Session::get('message') }}
                            </div>
                        @endif


                        <form action="" method="get">
                            <ul class="list-group">

                                @foreach($predmeti as $predmet)

                                    @IF(Auth::user()->studentprof == 'admin' || Auth::user()->studentprof == 'student')
                                    <li class="list-group-item" id="{!! $predmet['id'] !!}"><a href="{{ route('predmeti.edit', $predmet->id) }}">{{$predmet['predmet'] }}</a></li><br>

                                    @ELSEIF(Auth::user()->studentprof == 'profesor')
                                    <li class="list-group-item" id="">{{$predmet['predmet'] }}</li><br>
                                    @ENDIF

                                @endforeach
                            </ul>
                            </form>

                        @IF(Auth::user()->studentprof == 'student')
                            {!! Form::open(array('method' => 'GET', 'route' => array('predmeti.create'))) !!}
                            {!! Form::submit('Запиши предмет', array('name' => 'activation', 'class' => 'btn btn-info')) !!}
                            {!! Form::close() !!}
                        @ENDIF

                            @IF(Auth::user()->studentprof == 'admin')
                            <div class="form-group">
                                <div class="col-md-4">
                                    {!! Form::open(array('method' => 'GET', 'route' => 'predmeti.create')) !!}
                                    {!! Form::submit('Креирај нов предмет', array('class' => 'btn btn-success')) !!}
                                    {!! Form::close() !!}
                                </div>
                            @ENDIF

                                <div class="col-md-3">
                                    {!! Form::open(array('method' => 'GET', 'route' => '/')) !!}
                                    {!! Form::submit('Назад', array('class' => 'btn btn-warning')) !!}
                                    {!! Form::close() !!}
                                </div>
                            </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@extends('bottom')

resources/views/root/profesori.blade.php
@extends('top')
@extends('navbar')
@section('content')


    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading" style="text-align: center"><h1>Листа на професори</h1></div>
                    <div class="panel-body">

                    @if(Session::has('message'))
                        <div class="alert alert-success">
                            {{ Session::get('message') }}
                        </div>
                    @endif


                    <form action="" method="get">
                        <ul class="list-group">
                        @foreach($profesori as $profesor)

                            <li class="list-group-item" id="{!! $profesor['id'] !!}">
                    <a href="{{ route('profesori.edit', $profesor->id) }}">{{ $profesor['ime']. ' ' . $profesor['prezime'] }}</a>
                                @IF(Auth::user()->studentprof == 'admin')
                                    @if($profesor['activation'] == '0')

                                        {!! Form::open(array('method' => 'PATCH', 'route' => array('profesori.update', $profesor->id) )) !!}
                                        {!! Form::submit('Активирај', array('name' => 'activation', 'class' => 'btn btn-info')) !!}
                                        {!! Form::close() !!}

                                    @elseif($profesor['activation'] == '1')
                                        {!! Form::open(array('method' => 'PATCH', 'route' => array('profesori.update', $profesor->id) )) !!}
                                        {!! Form::submit('Деактивирај', array('name' => 'activation', 'class' => 'btn btn-danger')) !!}
                                        {!! Form::close() !!}
                                    @endif
                                @endif

                            @endforeach
                        </ul>
                    </form>

        <div class="form-group">
            <div class="col-md-4">
            {!! Form::open(array('method' => 'GET', 'route' => 'profesori.create')) !!}
            {!! Form::submit('Креирај нов професор', array('class' => 'btn btn-success')) !!}
            {!! Form::close() !!}
            </div>
            <div class="col-md-3">
            {!! Form::open(array('method' => 'GET', 'route' => '/')) !!}
            {!! Form::submit('Назад', array('class' => 'btn btn-warning')) !!}
            {!! Form::close() !!}
            </div>
        </div>

</div></div></div></div></div>

@stop

@extends('bottom')

resources/views/root/profil.blade.php
@extends('top')
@extends('navbar')
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading" style="text-align: center"><h1>Профил на {!! $currentUser['ime'] . " " . $currentUser['prezime'] !!}</h1></div>
                    <div class="panel-body">

                        @if(Session::has('message'))
                            <div class="alert alert-success">
                                {{ Session::get('message') }}
                            </div>
                        @endif

                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Грешка!</strong> Имаше проблем при внесување на податоците!<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach

                                </ul>
                            </div>
                        @endif


                        {!! Form::model($currentUser, array('method' => 'PATCH', 'class' => 'form-horizontal', 'route' => array('profil.update', $currentUser->id))) !!}
                        <div class="form-group">
                            {!!  Form::label('ime', 'Име' , ['class' => 'col-md-4 control-label']) !!}
                            <div class="col-md-6">
                                {!! Form::text('ime', $currentUser['ime'], ['class' => 'form-control'])  !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!!  Form::label('prezime', 'Презиме', ['class' => 'col-md-4 control-label']) !!}
                            <div class="col-md-6">
                                {!! Form::text('prezime', $currentUser['prezime'], ['class' => 'form-control'])  !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('email', 'Емаил', ['class' => 'col-md-4 control-label']) !!}
                            <div class="col-md-6">
                                {!! Form::email('email', $currentUser['email'], ['class' => 'form-control'])  !!}
                            </div>

                        </div>

                        <div class="form-group">
                            {!!  Form::label('password', 'Лозинка', ['class' => 'col-md-4 control-label']) !!}
                            <div class="col-md-6">
                                {!! Form::password('password', ['class' => 'form-control'])  !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!!  Form::label('password_confirmation', 'Потврдна лозинка', ['class' => 'col-md-4 control-label']) !!}
                            <div class="col-md-6">
                                {!! Form::password('password_confirmation', ['class' => 'form-control'])  !!}
                            </div>

                        </div>

                        <div class="form-group">
                        <div class="col-md-3" >
                            {!! Form::submit('Измени профил', ['class'=>'btn btn-primary']) !!}
                            {!! Form::close() !!}
                        </div>

                        <div class="col-md-3">
                            {!! Form::open(array('method' => 'GET', 'route' => '/')) !!}
                            {!! Form::submit('Назад', array('class' => 'btn btn-warning')) !!}
                            {!! Form::close() !!}
                        </div>
                            </div>

                        {!! Form::close() !!}

                    </div></div></div></div></div>


@stop

@extends('bottom')

resources/views/root/studenti.blade.php
@extends('top')
@extends('navbar')
@section('content')


    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading" style="text-align: center;"><h1>Листа на студенти</h1></div>
                    <div class="panel-body">

                        @if(Session::has('message'))
                            <div class="alert alert-success">
                                {{ Session::get('message') }}
                            </div>
                        @endif
                        @IF(Auth::user()->studentprof == 'admin')
                        <form action="" method="get">
                            <ul class="list-group">
                                @foreach($studenti as $student)

                                    <li class="list-group-item" id="{!! $student['id'] !!}"><a href="{{ route('studenti.edit', $student->id) }}">{{ $student['ime']. ' ' . $student['prezime'] }}</a></li><br>
                                    @IF(Auth::user()->studentprof == 'admin')
                                        @if($student['activation'] == '0')

                                            {!! Form::open(array('method' => 'PATCH', 'route' => array('studenti.update', $student->id) )) !!}
                                            {!! Form::submit('Активирај', array('name' => 'activation', 'class' => 'btn btn-info')) !!}
                                            {!! Form::close() !!}

                                        @elseif($student['activation'] == '1')
                                            {!! Form::open(array('method' => 'PATCH', 'route' => array('studenti.update', $student->id) )) !!}
                                            {!! Form::submit('Деактивирај', array('name' => 'activation', 'class' => 'btn btn-danger')) !!}
                                            {!! Form::close() !!}
                                        @endif
                                @ENDIF
                                @endforeach
                            </ul>
                        </form>
                            @ENDIF
                        @IF(Auth::user()->studentprof == 'admin')
                        <div class="form-group">
                            <div class="col-md-4">
                                {!! Form::open(array('method' => 'GET', 'route' => 'studenti.create')) !!}
                                {!! Form::submit('Креирај нов студент', array('class' => 'btn btn-success')) !!}
                                {!! Form::close() !!}
                            </div>
                        @ENDIF
                            @IF(Auth::user()->studentprof == 'student' || Auth::user()->studentprof == 'profesor' )
                            <form action="" method="get">
                            @foreach($predmeti as $predmet)
                                <li class="list-group-item" id="{!! $predmet['id'] !!}"><a href="{{ route('/lista', $predmet->id) }}">{{ $predmet['predmet']}}</a></li><br>
                                </form>
                            @endforeach
                            @ENDIF

                            <div class="col-md-3">
                                {!! Form::open(array('method' => 'GET', 'route' => '/')) !!}
                                {!! Form::submit('Назад', array('class' => 'btn btn-warning')) !!}
                                {!! Form::close() !!}
                            </div>
                        </div>

                    </div></div></div></div></div>

@stop

@extends('bottom')